### ISSUE TITLE
issue while uploading .xlsx

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#2]
dataset: AspenCompetitionGarden2015

While uploading "CompetitonGarden_MetaData.xlsx" user got this error (below).

I suspect this is because the spreadsheet was made on his Italian computer. I guess this is a good test for handling internationally formatted files.

I'll post a separate issue, but I also wondered how the importer would do with the Italian .csv files.

- Package ID: 52107669-7ccf-434d-aaa8-86df934fdd1e

- Message: Request Error

- Code: 3

- User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

- commit: 8fbba6fb8c076ab01243dc3f49107d2b8329f849

- version: v1.2-67-g8fbba6f

- branch: dev

**Comment by jrmerz** [comment]
So I peeked in at this dataset and say the fubar files.  There were two issues.
- The excel file had a non utf-8 character in the header (^C).  While this character isn't supported, it shouldn't fail, it should just be stripped out.
- The csv file was not comma separated (csv = comma separated values).  It used semicolons.

I have since patched the system with the two following improvements.
- Better support for stripping bad characters (non utf-8) from both excel and csv files.
- The UI now supports switching the CSV file delimiter.  This toggle is only shown for .csv and .spectra files.  The options are:
  - comma = ','
  - semicolon = ';'
  - tab = '\t'
  - other = user provided input

After pushing these changes, I retested the upload.  The excel file parsed and the CSV file parsed when switch to separator = semicolon.

Please test and verify everything is working.  And thanks for posting the details!

**Comment by ckingdon** [comment]
Sorry, I forgot to note that we got a "invalid utf-8 character" error at some point .. was making notes on my phone and notebook.

I should also note that, at first, it appeared that the .xlsx file hadn't uploaded at all. The page only offered the error (above), then continued to act as if it was uploading. Only when we reloaded the page, then  went to review the resources, did we realize that the files had actually been uploaded multiple times.

**Comment by jrmerz** [comment]
Ya, the UI throw up on the condition.  I will work to fix.  The resource was added but failed to parse.

We're the issues fixed now?

**Comment by ckingdon** [comment]
still working with AspenCompetitionGarden2015 ...

I tested the comma/decimal issue. Both files use ; for separator.

leaf_means_df_EcoSIS_ID_commadecimal.csv
commas used instead of of decimal point

leaf_means_df_EcoSIS_SID.csv
commas replaced with decimal point

For _commadecimal.csv the spectrum preview widget doesn't show the spectrum. For the 'conventional' file that uses decimal points the spectrum looks fine.

Can you add a decimal separator, just as you've done with the column separator?
