### ISSUE TITLE
Map is All the way zoomed on HyspIRI Dataset

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#24]
For HyspIRI dataset on the production site, on the published page (http://ecospectra.org/#result/fac4e3cb-7ebb-42d9-a7e3-1273114d4efa), the location is zoomed in all the way to a single point when the page is loaded. All of the other ones look fine. I checked the data page (http://data.ecospectra.org/dataset/nasa-hyspiri-california) and the location is boxed just like the rest. Only pointing it out because it is one of the example datasets we sent out. 

![screen shot 2016-02-16 at 10 24 36 pm copy](https://cloud.githubusercontent.com/assets/17035574/13099830/289d6c7e-d4fc-11e5-8a97-b2f41b056b6b.jpg)

Working on Firefox 44.0.2 on Mac OSX 10.7.5

**Comment by jrmerz** [comment]
There are two bounding boxes.  One is provided by the user, the other is calculated from the spectra if lat/lng's are given.  The spectra lat/lng bounding box has priority over the given user bounding box for zoom level, but both are drawn.  Since, in this case, all spectra are at one point, the map is zoomed in really far and the bbox is tiny.

This should probably be a little more zoomed out... but I like the data provided by the spectra overriding a rough sketch by a user.

**Comment by aidanmazur** [comment]
Good to know, no problem then. thanks for checking it out!
