### ISSUE TITLE
DOI applied to Dataset on Production but says it is not real

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#51]
For the dataset "Fresh Leaf Spectra to Estimate Leaf Morphology and Biochemistry for Northern Temperate Forests" (http://data.ecosis.org/import/?id=4a63d7ed-4c1e-40a7-8c88-ea0deea10072) it shows that there is a DOI applied to it, and under DOI it states "This is NOT a real DOI. Only datasets in production system (data.ecosis.org) will be given actual DOI numbers."

**Comment by jrmerz** [comment]
Thanks, that's just a bug with display text.  Will fix.  The DOI is assigned. 

http://dx.doi.org/10.21232/C2WC75

**Comment by jrmerz** [comment]
Actually, this looks like something different.  Looks like docker was started with it's base image, which installs the extension from the python egg so git was at detached head instead of master.  Switched back to master branch and all is well, though I need to investigate why a new image was used.

Closing this for now.
