### ISSUE TITLE
keywords don't show in search

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#7]
Not sure if this is a ckan issue, but for dataset "2015 Summer Conductance", the user entered several keywords during import, but they don't show up after the dataset is pushed to search.

**Comment by jrmerz** [comment]
I looked into the dataset and saw one keyword entered.  It was showing in CKAN but not in search.  I re-pushed the dataset and the keyword now shows.  Not totally sure what the issue was.  It's possible the old keyword input was causing some badness.  I am going to close this for now.  But lets re-open if it happens again.
